version: '3.4'

services:
  server:
  build: server/
  command: npm install || npm run dev
  ports: 
  - 8080:8080

  client:
    
    build: '/client'
    volumes:
    - .:/app
    - /app/node_modules
    stdun_open: true
    tty: true
    network_mode: host
    depends_on:
    - server

      
