version: '3.4'

services:
  server:
    build: ./server
    ports: 
      - 8080:8080

  client:    
    build: ./client
    stdin_open: true
    tty: true
    ports:
      - 5173:5173
    depends_on:
      - server

      
